import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ✅ ใช้ Inter แทน Geist
import "./globals.css";

// โหลดฟอนต์ Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stall Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ เรียกใช้ className ของ Inter ตรงนี้ */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}